const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const dotenv = require('dotenv');

dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;

// Middleware
app.use(cors());
app.use(express.json());

// Routes
const authRoutes = require('./routes/auth');
const inventoryRoutes = require('./routes/inventory');
const analysisRoutes = require('./routes/analysis');

app.use('/api/auth', authRoutes);
app.use('/api/inventory', inventoryRoutes);
app.use('/api/analysis', analysisRoutes);

app.get('/', (req, res) => {
  res.send('Food Freshness API is running');
});

// Database
const connectDB = async () => {
    try {
        let uri = process.env.MONGODB_URI;
        // If it's a dummy value generated by Render, use an in-memory DB so the app still works!
        if (!uri || uri.length < 20 || !uri.startsWith('mongodb')) {
            console.log("No valid MONGODB_URI detected. Spinning up in-memory MongoDB for zero-config presentation...");
            const { MongoMemoryServer } = require('mongodb-memory-server');
            // Render uses Debian 12 which requires MongoDB 7.0.3+
            const mongoServer = await MongoMemoryServer.create({ instance: { version: '7.0.14' } });
            uri = mongoServer.getUri();
        }
        await mongoose.connect(uri);
        console.log('Connected to MongoDB');
        app.listen(PORT, () => {
            console.log(`Server is running on port ${PORT}`);
        });
    } catch (err) {
        console.error('MongoDB connection error:', err);
    }
};
connectDB();
